### ISSUE TITLE
Implement RFC0052: Graceful Stack Upgrades

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/python#509]
[RFC](https://github.com/paketo-buildpacks/rfcs/blob/main/text/0052-graceful-stack-upgrades.md)

## Summary

All Paketo Buildpacks should support graceful stack upgrades between the current Bionic and Jammy stacks. For most buildpacks, this should not require any changes, but for some buildpacks, layers created in previous builds that would normally be reused should be recreated if the stack ID changes.

## Action Item
Consider what types of buildpacks would be impacted by a stack upgrade and make any relevant changes that would help to mitigate issues caused by that upgrade. If there is no work to be done, please comment on this issue explaining the context that helped to arrive at that conclusion.

**Comment by fg-j** [comment]
### Buildpacks that do not require changes
- cpython, pip, pipenv, miniconda, poetry : these all use [`postal.Resolve()`](https://github.com/paketo-buildpacks/packit/blob/9c33469b56d8d1f670fdc0a97353aeb63a34a0ff/postal/service.go#L68) to install dependencies. The function considers stack ID when determining which dependency to install; if the stack upgrade requires a new version of the dependency, this is handled automatically
- procfile, environment-variables, ca-certificates, image-labels, watchexec: these utility buildpacks do not cache artifacts between builds; there's nothing to recreate
- python-start, poetry-start: these buildpacks don't create layers; they simply contribute launch processes. There's nothing to do here.

### Buildpacks that may require changes
- pip-install: the buildpack [creates a layer](https://github.com/paketo-buildpacks/pip-install/blob/9a67843dde46765c6a8250abc92ef15174b4c0bf/build.go#L54) for the pip cache directory, which it caches for rebuilds. I haven't yet been able to produce an instance where an app breaks because the buildpack restored the cache across stack upgrades. However, the most "conservative" option is to empty the cache if the stack ID changes. There's a performance penalty, but users should rarely encounter it in the course of (re)building their apps.

- pipenv-install: as with pip-install, the buildpack [creates a layer](https://github.com/paketo-buildpacks/pipenv-install/blob/477077e97039508721af09ae3bff6db90d47b516/build.go#L63) where the pipenv cache is stored. Likewise, I have not yet produced a broken app by upgrading the stack without clearing the cache. Clearing the cache is, again, the "safest" choice.

- poetry-install: the buildpack also [creates a layer](https://github.com/paketo-buildpacks/poetry-install/blob/985551bae57ed1dca702512cbeff290d793d89d7/build.go#L55) to store the poetry cache.  I have not yet produced a broken app by upgrading the stack without clearing the cache. Clearing the cache is, again, the "safest" choice.

I will continue for another day or so to try and identify some failure modes for stack upgrades before deciding whether to do nothing or conservatively empty the caches when stack ID changes between builds.

**Comment by robdimsdale** [comment]
Awesome investigation @fg-j !

@jpena-r7 did you have any concrete examples of packages that would likely fail during stack upgrade (e.g. `mysqlclient`)?

**Comment by robdimsdale** [comment]
Also my instinct is that any package that dynamically links against `libssl` will break, because we know that bionic has `libssl1.1` and jammy has `libssl3` and they are not ABI-compatible.

However, I don't know off the top of my head which packages would do that.

**Comment by fg-j** [comment]
@robdimsdale I'll give that a try – I'm not sure it'll be an issue though, since the install process always runs in all of these buildpacks.

**Comment by robdimsdale** [comment]
Wow, nice detective work, @fg-j ! I didn't know about the python `OpenSSL` module or its `debug` method.

Running that command against bionic and Jammy, I see that in both cases the `cryptography` library was compiled against `openssl` version 3, despite the fact that the runtime version is different - version 1 for Bionic and version 3 for Jammy.

Bionic:
```
> python3 -m OpenSSL.debug
pyOpenSSL: 22.0.0
cryptography: 38.0.1
cffi: 1.15.1
cryptography's compiled against OpenSSL: OpenSSL 3.0.5 5 Jul 2022
cryptography's linked OpenSSL: OpenSSL 3.0.5 5 Jul 2022
Python's OpenSSL: OpenSSL 1.1.1  11 Sep 2018
```

Jammy:
```
> python3 -m OpenSSL.debug
pyOpenSSL: 22.0.0
cryptography: 38.0.1
cffi: 1.15.1
cryptography's compiled against OpenSSL: OpenSSL 3.0.5 5 Jul 2022
cryptography's linked OpenSSL: OpenSSL 3.0.5 5 Jul 2022
Python's OpenSSL: OpenSSL 3.0.2 15 Mar 2022
```

I'm genuinely surprised that this works, as we've seen similar failures with other tools/applications (like python itself) when the runtime version is different than the version the tool was compiled against.

Given this is the behavior of the libraries, not the toolchain (i.e. `pip`) I think we can extrapolate these findings to all package managers we support (i.e. `pipenv`, `poetry` and `conda`).

I'm surprised, but satisfied. I think we can preserve the existing cache rather than conservatively blowing it away when the stack changes.

Thank you for the investigation efforts!

**Comment by jpena-r7** [comment]
I just verified that `mysqlclient` works correctly. I tested this because I was already testing out building a python app with `mysqlclient` on another stack and wanted to confirm the same behavior as what you found in `OpenSSL`.

I built it first on bionic and then on jammy (full builders).

I believe this shows that the cached pip install layer was reused when I installed on jammy.
```
===> RESTORING
[restorer] Restoring metadata for "paketo-buildpacks/ca-certificates:helper" from app image
[restorer] Restoring metadata for "paketo-buildpacks/cpython:cpython" from app image
[restorer] Restoring metadata for "paketo-buildpacks/pip:pip" from cache
[restorer] Restoring metadata for "paketo-buildpacks/pip-install:packages" from app image
[restorer] Restoring metadata for "paketo-buildpacks/pip-install:cache" from cache
[restorer] Restoring data for "paketo-buildpacks/cpython:cpython" from cache
[restorer] Restoring data for "paketo-buildpacks/pip:pip" from cache
[restorer] Restoring data for "paketo-buildpacks/pip-install:cache" from cache
[restorer] Restoring data for "paketo-buildpacks/pip-install:packages" from cache
[restorer] Restoring data for SBOM from cache
```

Here is the output showing that mysqlclient works on both.
```
➜  stack-upgrade-testing docker run -it test-python-app-mysql
VERSION="18.04.6 LTS (Bionic Beaver)"
MySQLdb.version_info: (2, 1, 1, 'final', 0)
MySQLdb.get_client_info(): 10.2.9
MySQLdb.apilevel: 2.0
➜  stack-upgrade-testing docker run -it test-python-app-mysql
VERSION="22.04.1 LTS (Jammy Jellyfish)"
MySQLdb.version_info: (2, 1, 1, 'final', 0)
MySQLdb.get_client_info(): 3.2.6
MySQLdb.apilevel: 2.0
➜  stack-upgrade-testing 
```

Python script (for reference)
```
import subprocess
import MySQLdb

subprocess.run(["grep", "VERSION=", "/etc/os-release"])

print(f"MySQLdb.version_info: {MySQLdb.version_info}")
print(f"MySQLdb.get_client_info(): {MySQLdb.get_client_info()}")
print(f"MySQLdb.apilevel: {MySQLdb.apilevel}")
```

**Comment by robdimsdale** [comment]
@jpena-r7 thank you for sharing! Yes, that looks like the cache is being re-used across the app builds.

Given that we haven't found any issues with the most likely candidates, I'm leaning towards preserving the cache - at least until we get feedback that some library failed to work after stack upgrade.

@paketo-buildpacks/python-maintainers any objections to closing this issue as "no action needed"?

**Comment by robdimsdale** [comment]
Discussed offline with Python maintainers - no objections to closing this issue as "not needed".
